#!/bin/sh

aws s3 mb s3://${BUCKET_NAME}
sam build
sam package --template-file .aws-sam/build/template.yaml  --output-template-file ${STAGE_NAME}-packaged.yaml --s3-bucket ${BUCKET_NAME}
sam deploy --template-file ${STAGE_NAME}-packaged.yaml --stack-name ${STACK_NAME} --capabilities CAPABILITY_IAM --parameter-overrides Token=${TOKEN} Environment=${STAGE_NAME} Host=${HOST} Stack=${STACK_NAME}
